In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------- ----------------- 5.5/9.8 MB 30.5 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 29.2 MB/s eta 0:00:00
Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   --------------------- ------------------ 6.8/12.5 MB 32.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.5 MB 32.0 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 23.6 MB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.2 pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: numpy in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (2.5.2)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting matplotlib
  Downloading matplotlib-3.11.1-cp312-cp312-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.1-cp312-cp312-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   --------------------------------- ------ 7.9/9.3 MB 40.7 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 36.3 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 22.4 MB/s eta 0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------  7.1/7.2 MB 33.6 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 29.8 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.1 pillow-12.3.0 pyparsing-3.3.2

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\440 g7\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\440 g7\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#Carga desde un archivo .csv sin indice
df = pd.read_csv('Citas_Digital_Filtrado.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       660 non-null    str
 1   Fecha                                     75 non-null     str
 2   Nombre Cliente                            655 non-null    str
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           641 non-null    str
 5   Potencial de compra                       602 non-null    str
 6   PDM                                       675 non-null    float64
 7   SDC                                       674 non-null    float64
 8   Venta                                     671 non-null    float64
 9   Asesor Asignado                           644 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: float64(3), str(13)
memory usage: 84.6 KB

In [31]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
df1= df.drop(['Unnamed: 15'], axis=1)
df1

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
673,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN
674,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN
675,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN

In [32]:
#Identificar valores nulos por columna
valores_nulos=df1.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [33]:
#Identificar valores nulos por dataframe
valores_nulos=df1.isnull().sum().sum()
valores_nulos

np.int64(2897)

In [34]:
#Realizamos una copia del dataframe
df2=df1.copy()

In [35]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df2["Asesor Asignado"] =df2["Asesor Asignado"].ffill()

In [36]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [37]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
df2["Nombre Cliente "] =df2["Nombre Cliente "].bfill()

In [39]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [41]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
df2["BDC "] =df2["BDC "].ffill()

In [42]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [43]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
df2["Estatus de Lead"] =df2["Estatus de Lead"].bfill()

In [44]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [45]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
df2["¿Por que no ha visitado la agencia?"] =df2["¿Por que no ha visitado la agencia?"].ffill()

In [46]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [ ]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
df2["¿Por que no hay solicitud de credito?"] =df2["¿Por que no hay solicitud de credito?"].ffill()

In [51]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [ ]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
df2["¿Por que no hubo prueba de manejo ?"] =df2["¿Por que no hubo prueba de manejo ?"].ffill()

In [55]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [ ]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
df2["¿Por que no hubo proceso wow?"] =df2["¿Por que no hubo proceso wow?"].ffill()

In [57]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [60]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
df2["¿Por que se asigno antes de vistar piso?"] =df2["¿Por que se asigno antes de vistar piso?"].bfill()

In [61]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?      0
dtype: int64

In [62]:
df2["Venta"]= df2["Venta"].fillna(0) 
df2

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,Ya visito la agencia,depende del padres,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,Ya visito la agencia,depende del padres,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
673,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,Ya visito la agencia,depende del padres,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
674,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,Ya visito la agencia,depende del padres,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita
675,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,Ya visito la agencia,depende del padres,Ya realizo prueba de manejo,Recibio la atencion,Se asigno en la visita

In [65]:
df2["SDC"]= df2["SDC"].fillna(0)

In [66]:
df2["PDM"]= df2["PDM"].fillna(0)

In [67]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                                0
Telefono                                    674
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?      0
dtype: int64

In [68]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
df2["Fecha"] =df2["Fecha"].bfill()

In [72]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
df2["Telefono "] =df2["Telefono "].fillna("Sin teléfono")

In [76]:
#Convertir la columna a número (float)
df2["Potencial de compra"] = pd.to_numeric(df2["Potencial de compra"], errors='coerce')

#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
df2["Potencial de compra"]=df2["Potencial de compra"].fillna(round(df2["Potencial de compra"].median(),1))

In [77]:
#Corroboramos valores nulos
valores_nulos=df2.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [78]:
#Convertir DataFrame a CSV
df2.to_csv("Citas_Digital_sin_nulos.csv")